version: "3.4"

name: myapi-h2

services:
  h2:
    image: oscarfonts/h2:latest
    container_name: h2-database
    restart: always
    ports:
      - "1521:1521"  # H2 Database TCP Port
      - "81:81"  # H2 Console Port
    volumes:
      - ./h2-data:/opt/h2-data  # Persistent storage for H2 database files
    networks:
      - network-proyectoapi

  app:
    image: proyectoapi
    container_name: proyectoapi
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.application.name": "proyectoapi",
               "spring.datasource.url": "jdbc:h2:tcp://h2-database:1521/./testdb",
               "spring.datasource.username": "sa",
               "spring.datasource.password": "password",
               "spring.datasource.driverClassName": "org.h2.Driver",
               "spring.jpa.database-platform": "org.hibernate.dialect.H2Dialect",
               "spring.jpa.hibernate.ddl-auto": "create-drop",
               "spring.h2.console.enabled": "true",
               "server.port": "$SPRING_PORT"
             }'
    depends_on:
      - h2
    restart: on-failure
    networks:
      - network-proyectoapi

networks:
  network-proyectoapi:
    driver: bridge
